# Generated by Django 6.0.5 on 2026-09-24 09:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_biometricslog_arm_cm_biometricslog_chest_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=64)),
                ('value', models.JSONField()),
                ('updated_at', models.DateTimeField()),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_entries', to='profiles.userprofile')),
            ],
            options={
                'indexes': [models.Index(fields=['profile', 'key'], name='userstate_u_profile_8c4cbe_idx')],
                'constraints': [models.UniqueConstraint(fields=('profile', 'key'), name='unique_profile_key')],
            },
        ),
    ]
