# Generated by Django 6.0.5 on 2026-06-12 08:42

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0002_biometricslog_arm_cm_biometricslog_chest_cm_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('SPORT', 'Deporte'), ('MMA', 'MMA'), ('GYM', 'Gimnasio')], max_length=8)),
                ('title', models.CharField(blank=True, default='', max_length=80)),
                ('started_at', models.DateTimeField(db_index=True)),
                ('duration_sec', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(86400)])),
                ('rpe', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('kcal', models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(20000)])),
                ('note', models.TextField(blank=True, default='')),
                ('detail', models.JSONField(blank=True, null=True)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('XIAOMI', 'Xiaomi'), ('OTHER', 'Other')], default='MANUAL', max_length=12)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='profiles.userprofile')),
            ],
            options={
                'ordering': ('-started_at', '-id'),
                'indexes': [models.Index(fields=['profile', 'started_at'], name='activities__profile_548680_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('profile', 'source', 'external_id'), name='unique_activity_external_id_per_source')],
            },
        ),
    ]
