# Generated by Django 6.0.5 on 2026-06-01 10:45

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=6, null=True)),
                ('height_cm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('dominant_stance', models.CharField(blank=True, choices=[('ORTHODOX', 'Orthodox'), ('SOUTHPAW', 'Southpaw'), ('SWITCH', 'Switch')], max_length=8, null=True)),
                ('preferred_units', models.CharField(choices=[('METRIC', 'Metric'), ('IMPERIAL', 'Imperial')], default='METRIC', max_length=8)),
                ('timezone', models.CharField(default='UTC', max_length=64)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BiometricsLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('body_fat_pct', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True)),
                ('resting_heart_rate', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('sleep_quality_score', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('hrv_ms', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(db_index=True, default=None)),
                ('source', models.CharField(choices=[('MANUAL', 'Manual'), ('GARMIN', 'Garmin'), ('APPLE_HEALTH', 'Apple Health'), ('WHOOP', 'Whoop'), ('OTHER', 'Other')], default='MANUAL', max_length=12)),
                ('external_id', models.CharField(blank=True, max_length=128, null=True)),
                ('raw_payload', models.JSONField(blank=True, null=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='biometrics', to='profiles.userprofile')),
            ],
            options={
                'ordering': ('-timestamp',),
                'constraints': [models.UniqueConstraint(condition=models.Q(('external_id__isnull', False)), fields=('profile', 'source', 'external_id'), name='unique_external_id_per_source')],
            },
        ),
    ]
