# Generated by Django 6.0.5 on 2026-06-11 12:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='biometricslog',
            name='arm_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricslog',
            name='chest_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricslog',
            name='hip_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricslog',
            name='neck_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricslog',
            name='thigh_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='biometricslog',
            name='waist_cm',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='biometricslog',
            name='source',
            field=models.CharField(choices=[('MANUAL', 'Manual'), ('GARMIN', 'Garmin'), ('APPLE_HEALTH', 'Apple Health'), ('WHOOP', 'Whoop'), ('XIAOMI', 'Xiaomi'), ('OTHER', 'Other')], default='MANUAL', max_length=12),
        ),
        migrations.CreateModel(
            name='ProgressPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='progress/%Y/%m/')),
                ('taken_at', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='profiles.userprofile')),
            ],
            options={
                'ordering': ('-taken_at', '-id'),
            },
        ),
    ]
